apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "http://localhost:8082/login"
    nginx.ingress.kubernetes.io/auth-url: "http://host.docker.internal:8088/validate"
    nginx.ingress.kubernetes.io/auth-snippet: | 
      if ( $request_uri ~* "^/login") {
          return 200;
      }

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-application-service 
            port:
              number: 80
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: external-application-service-backend 
            port:
              number: 80
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: external-auth-service 
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: external-application-service 
spec:
  type: ExternalName
  externalName: host.docker.internal 
  ports:
  - port: 80
    targetPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: external-application-service-backend
spec:
  type: ExternalName
  externalName: host.docker.internal 
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: external-auth-service 
spec:
  type: ExternalName
  externalName: host.docker.internal 
  ports:
  - port: 80
    targetPort: 8088


# Install Nginx Ingress:
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx    
# helm repo update
# helm install nginx-ingress ingress-nginx/ingress-nginx --namespace nginx --create-namespace 
# helm upgrade nginx-ingress ingress-nginx/ingress-nginx --namespace nginx --create-namespace --set controller.allowSnippetAnnotations=true --set controller.replicaCount=3
