apiVersion: v1
kind: Service
metadata:
  name: kafka-3-external
spec:
  ports:
    - port: 9094
      targetPort: 9094
  selector:
    app: kafka-3
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-3-internal
spec:
  ports:
    - port: 29094 
      targetPort: 29094
  selector:
    app: kafka-3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-3-internal.default.svc.cluster.local:29094,EXTERNAL://localhost:9094"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:29094,EXTERNAL://0.0.0.0:9094"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: "LISTENERS"
              value: "PLAINTEXT://:9094"