apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-init-script
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;
    CREATE USER IF NOT EXISTS 'auth-service'@'%' IDENTIFIED BY 'geheim34059843095843095';
    GRANT ALL PRIVILEGES ON authdb.* TO 'auth-service'@'%';
    FLUSH PRIVILEGES;
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
      - name: authdb 
        image: surrealdb/surrealdb:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: db-init-script-volume
          mountPath: /docker-entrypoint-initdb.d
        args: ["start", "--log", "trace", "--user", "root", "--pass", "root", "memory"]
        ports:
        - containerPort: 8000
      volumes:
      - name: db-init-script-volume
        configMap:
          name: auth-db-init-script
      automountServiceAccountToken: false
---

apiVersion: v1
kind: Service
metadata:
  name: authdb-service
spec:
  ports:
  - port: 8000
  selector:
    app: authdb
  type: ClusterIP
---
