apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webapp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test-webapp
  template:
    metadata:
      labels:
        app: test-webapp
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: test-webapp-clusterip
spec:
  type: ClusterIP  
  selector:
    app: test-webapp 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
---