apiVersion: v1
kind: Service
metadata:
  name: kafka-1-external
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-1
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-1-internal
spec:
  ports:
    - port: 29092 
      targetPort: 29092
  selector:
    app: kafka-1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-1-internal.default.svc.cluster.local:29092,EXTERNAL://localhost:9092"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: "LISTENERS"
              value: "PLAINTEXT://:9092"